from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter, portrait
from reportlab.lib.colors import HexColor

def generate():
    c = canvas.Canvas("Digos_Job_Board_Strategy_Infographic.pdf", pagesize=portrait(letter))
    width, height = portrait(letter)

    # Background
    c.setFillColor(HexColor("#111827")) # Dark workspace theme
    c.rect(0, 0, width, height, stroke=0, fill=1)

    # Title
    c.setFillColor(HexColor("#ffffff"))
    c.setFont("Helvetica-Bold", 24)
    c.drawString(40, height - 60, "Digos Job Board: Strategy & UI Infographic")
    
    c.setFillColor(HexColor("#9ca3af"))
    c.setFont("Helvetica", 10)
    c.drawString(40, height - 80, "Synthesizing Local Pain Points with Modern UI/UX Solutions")

    # Section 1
    c.setFillColor(HexColor("#3b82f6")) # brand-500
    c.setFont("Helvetica-Bold", 16)
    c.drawString(40, height - 120, "1. The Local Hiring Problem")

    c.setFillColor(HexColor("#d1d5db"))
    c.setFont("Helvetica", 11)
    c.drawString(40, height - 145, "• The 'Black Hole': Rampant ghosting & zero status updates.")
    c.drawString(40, height - 165, "• Missing Context: Standard boards ignore trike routes & barangay specifics.")
    c.drawString(40, height - 185, "• 'How Po?' Dilemma: Facebook groups are chaotic and unfilterable.")

    # Section 2
    c.setFillColor(HexColor("#3b82f6"))
    c.setFont("Helvetica-Bold", 16)
    c.drawString(40, height - 230, "2. Digos-First Feature Solutions")

    # Feature 1
    c.setFillColor(HexColor("#1f2937"))
    c.roundRect(40, height - 310, width - 80, 60, 10, stroke=0, fill=1)
    c.setFillColor(HexColor("#10b981"))
    c.setFont("Helvetica-Bold", 12)
    c.drawString(55, height - 275, "Hyperlocal Commute Tags")
    c.setFillColor(HexColor("#9ca3af"))
    c.setFont("Helvetica", 10)
    c.drawString(55, height - 295, "Search by Barangay. Tags like '1 trike ride from Gaisano' or 'Walk from Market'.")

    # Feature 2
    c.setFillColor(HexColor("#1f2937"))
    c.roundRect(40, height - 390, width - 80, 60, 10, stroke=0, fill=1)
    c.setFillColor(HexColor("#10b981"))
    c.setFont("Helvetica-Bold", 12)
    c.drawString(55, height - 355, "Verified Local Employer Badges")
    c.setFillColor(HexColor("#9ca3af"))
    c.setFont("Helvetica", 10)
    c.drawString(55, height - 375, "Scam-shield verification cross-referenced with City Hall business permits.")

    # Section 3
    c.setFillColor(HexColor("#3b82f6"))
    c.setFont("Helvetica-Bold", 16)
    c.drawString(40, height - 440, "3. UI/UX Paradigm Shifts Explored")

    c.setFillColor(HexColor("#d1d5db"))
    c.setFont("Helvetica", 11)
    c.drawString(40, height - 465, "Five radical concepts were explored to break the 'job graveyard' look:")

    y = height - 490
    concepts = [
        "A. Interactive Commute Map: Spatial browsing like Airbnb.",
        "B. Rapid Swipe Deck: High engagement mobile micro-cards like Tinder.",
        "C. Editorial Bento Grid: Curated lifestyle magazine layout (Apple-style).",
        "D. Power-User Console: Sleek, high-density tabular data (Linear-style).",
        "E. Master-Detail Split Pane: Zero page-reloads dual workspace (Slack-style)."
    ]

    for concept in concepts:
        c.drawString(50, y, concept)
        y -= 25

    c.setFillColor(HexColor("#3b82f6"))
    c.roundRect(40, y - 60, width - 80, 45, 10, stroke=0, fill=1)
    c.setFillColor(HexColor("#ffffff"))
    c.setFont("Helvetica-Bold", 12)
    c.drawString(55, y - 35, "★ Final UI Decision: The Master-Detail Split Pane")
    c.setFont("Helvetica", 10)
    c.drawString(55, y - 50, "Provides a lightning-fast, desktop-app feel that respects user time and screen space.")

    # Footer
    c.setFillColor(HexColor("#4b5563"))
    c.setFont("Helvetica", 9)
    c.drawCentredString(width / 2, 40, "Generated by Antigravity | Based on Digos Job Board R&D Reports")

    c.save()
    print("PDF generated successfully.")

if __name__ == "__main__":
    generate()
